/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajout_d_une_liste_electoral (void)
{
  GtkWidget *Ajout_d_une_liste_electoral;
  GtkWidget *fixed1;
  GtkWidget *nomliste;
  GtkWidget *idtete;
  GtkWidget *hseparator1;
  GtkObject *nbcondidat_adj;
  GtkWidget *nbcondidat;
  GtkWidget *jour_liste;
  GtkWidget *mois_liste;
  GtkWidget *anneliste;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *buttonajoutliste;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  Ajout_d_une_liste_electoral = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout_d_une_liste_electoral, 0, 0);
  gtk_window_set_title (GTK_WINDOW (Ajout_d_une_liste_electoral), _("Ajout d'une liste \303\251lectorale"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Ajout_d_une_liste_electoral), fixed1);
  gtk_widget_set_size_request (fixed1, 450, 650);

  nomliste = gtk_entry_new ();
  gtk_widget_show (nomliste);
  gtk_fixed_put (GTK_FIXED (fixed1), nomliste, 130, 120);
  gtk_widget_set_size_request (nomliste, 208, 32);
  gtk_tooltips_set_tip (tooltips, nomliste, _("Saisir le nom de votre liste ici"), NULL);
  gtk_entry_set_text (GTK_ENTRY (nomliste), _("Nom de la liste"));
  gtk_entry_set_invisible_char (GTK_ENTRY (nomliste), 8226);

  idtete = gtk_entry_new ();
  gtk_widget_show (idtete);
  gtk_fixed_put (GTK_FIXED (fixed1), idtete, 130, 232);
  gtk_widget_set_size_request (idtete, 208, 32);
  gtk_tooltips_set_tip (tooltips, idtete, _("Saisir l'id du t\303\252te de liste"), NULL);
  gtk_entry_set_text (GTK_ENTRY (idtete), _("ID"));
  gtk_entry_set_invisible_char (GTK_ENTRY (idtete), 8226);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 192, 72);
  gtk_widget_set_size_request (hseparator1, 16, 16);

  nbcondidat_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nbcondidat = gtk_spin_button_new (GTK_ADJUSTMENT (nbcondidat_adj), 1, 0);
  gtk_widget_show (nbcondidat);
  gtk_fixed_put (GTK_FIXED (fixed1), nbcondidat, 130, 344);
  gtk_widget_set_size_request (nbcondidat, 88, 24);

  jour_liste = gtk_entry_new ();
  gtk_widget_show (jour_liste);
  gtk_fixed_put (GTK_FIXED (fixed1), jour_liste, 130, 456);
  gtk_widget_set_size_request (jour_liste, 48, 40);
  gtk_tooltips_set_tip (tooltips, jour_liste, _("Saisir le jour"), NULL);
  gtk_entry_set_text (GTK_ENTRY (jour_liste), _("    JJ"));
  gtk_entry_set_invisible_char (GTK_ENTRY (jour_liste), 8226);

  mois_liste = gtk_entry_new ();
  gtk_widget_show (mois_liste);
  gtk_fixed_put (GTK_FIXED (fixed1), mois_liste, 178, 456);
  gtk_widget_set_size_request (mois_liste, 48, 40);
  gtk_tooltips_set_tip (tooltips, mois_liste, _("Saisir le mois"), NULL);
  gtk_entry_set_text (GTK_ENTRY (mois_liste), _("  MM"));
  gtk_entry_set_invisible_char (GTK_ENTRY (mois_liste), 8226);

  anneliste = gtk_entry_new ();
  gtk_widget_show (anneliste);
  gtk_fixed_put (GTK_FIXED (fixed1), anneliste, 224, 456);
  gtk_widget_set_size_request (anneliste, 80, 40);
  gtk_entry_set_text (GTK_ENTRY (anneliste), _("    AAAA"));
  gtk_entry_set_invisible_char (GTK_ENTRY (anneliste), 8226);

  label2 = gtk_label_new (_("Election municipale"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 100, 24);
  gtk_widget_set_size_request (label2, 240, 32);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label2), 0.46, 0.42);
  gtk_misc_set_padding (GTK_MISC (label2), 3, 0);

  label1 = gtk_label_new (_("Saisir le nom de la liste"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 100, 104);
  gtk_widget_set_size_request (label1, 208, 16);

  label3 = gtk_label_new (_("Saisi l'identifiant du t\303\252te de liste"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 100, 192);
  gtk_widget_set_size_request (label3, 240, 32);

  label4 = gtk_label_new (_("Nombre de condidat"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 100, 312);
  gtk_widget_set_size_request (label4, 176, 24);

  label5 = gtk_label_new (_("Saisir la datte"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 100, 424);
  gtk_widget_set_size_request (label5, 128, 24);

  buttonajoutliste = gtk_button_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (buttonajoutliste);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajoutliste, 134, 600);
  gtk_widget_set_size_request (buttonajoutliste, 152, 48);

  g_signal_connect ((gpointer) buttonajoutliste, "clicked",
                    G_CALLBACK (on_buttonajoutliste_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_d_une_liste_electoral, Ajout_d_une_liste_electoral, "Ajout_d_une_liste_electoral");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, nomliste, "nomliste");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, idtete, "idtete");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, nbcondidat, "nbcondidat");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, jour_liste, "jour_liste");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, mois_liste, "mois_liste");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, anneliste, "anneliste");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, label1, "label1");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajout_d_une_liste_electoral, buttonajoutliste, "buttonajoutliste");
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_d_une_liste_electoral, tooltips, "tooltips");

  return Ajout_d_une_liste_electoral;
}

GtkWidget*
create_ajout_cond (void)
{
  GtkWidget *ajout_cond;
  GtkWidget *fixed2;
  GtkWidget *nom_condidat1;
  GtkWidget *prenom_condidat1;
  GtkWidget *entry3;
  GtkWidget *ajout_con1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  ajout_cond = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_cond), _("window1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout_cond), fixed2);

  nom_condidat1 = gtk_entry_new ();
  gtk_widget_show (nom_condidat1);
  gtk_fixed_put (GTK_FIXED (fixed2), nom_condidat1, 54, 100);
  gtk_widget_set_size_request (nom_condidat1, 104, 32);
  gtk_tooltips_set_tip (tooltips, nom_condidat1, _("Saisir le nom"), NULL);
  gtk_entry_set_text (GTK_ENTRY (nom_condidat1), _("Nom"));
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_condidat1), 8226);

  prenom_condidat1 = gtk_entry_new ();
  gtk_widget_show (prenom_condidat1);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom_condidat1, 158, 100);
  gtk_widget_set_size_request (prenom_condidat1, 96, 32);
  gtk_tooltips_set_tip (tooltips, prenom_condidat1, _("Saisir le prenom"), NULL);
  gtk_entry_set_text (GTK_ENTRY (prenom_condidat1), _("Prenom"));
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_condidat1), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 256, 100);
  gtk_widget_set_size_request (entry3, 120, 32);
  gtk_tooltips_set_tip (tooltips, entry3, _("Saisir l'id du condidat"), NULL);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("ID condidat"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  ajout_con1 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajout_con1);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout_con1, 372, 100);
  gtk_widget_set_size_request (ajout_con1, 72, 32);

  g_signal_connect ((gpointer) ajout_con1, "clicked",
                    G_CALLBACK (on_ajout_con1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_cond, ajout_cond, "ajout_cond");
  GLADE_HOOKUP_OBJECT (ajout_cond, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout_cond, nom_condidat1, "nom_condidat1");
  GLADE_HOOKUP_OBJECT (ajout_cond, prenom_condidat1, "prenom_condidat1");
  GLADE_HOOKUP_OBJECT (ajout_cond, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ajout_cond, ajout_con1, "ajout_con1");
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_cond, tooltips, "tooltips");

  return ajout_cond;
}

GtkWidget*
create_vote_id_mp (void)
{
  GtkWidget *vote_id_mp;
  GtkWidget *fixed3;
  GtkWidget *identifiant_vote;
  GtkWidget *mot_passecond;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *Bouton_vote;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  vote_id_mp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (vote_id_mp), _("window2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (vote_id_mp), fixed3);

  identifiant_vote = gtk_entry_new ();
  gtk_widget_show (identifiant_vote);
  gtk_fixed_put (GTK_FIXED (fixed3), identifiant_vote, 112, 96);
  gtk_widget_set_size_request (identifiant_vote, 160, 27);
  gtk_tooltips_set_tip (tooltips, identifiant_vote, _("Saisir l'identifiant"), NULL);
  gtk_entry_set_text (GTK_ENTRY (identifiant_vote), _("Identifiant"));
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant_vote), 8226);

  mot_passecond = gtk_entry_new ();
  gtk_widget_show (mot_passecond);
  gtk_fixed_put (GTK_FIXED (fixed3), mot_passecond, 112, 176);
  gtk_widget_set_size_request (mot_passecond, 160, 27);
  gtk_tooltips_set_tip (tooltips, mot_passecond, _("Saisir le mot de passe"), NULL);
  gtk_entry_set_text (GTK_ENTRY (mot_passecond), _("mot de passe"));
  gtk_entry_set_invisible_char (GTK_ENTRY (mot_passecond), 8226);

  label7 = gtk_label_new (_("Saisir votre mot de passe"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 104, 152);
  gtk_widget_set_size_request (label7, 168, 24);

  label6 = gtk_label_new (_("Saisir votre identifiant"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 104, 64);
  gtk_widget_set_size_request (label6, 184, 24);

  Bouton_vote = gtk_button_new_with_mnemonic (_("Voter"));
  gtk_widget_show (Bouton_vote);
  gtk_fixed_put (GTK_FIXED (fixed3), Bouton_vote, 152, 280);
  gtk_widget_set_size_request (Bouton_vote, 66, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (vote_id_mp, vote_id_mp, "vote_id_mp");
  GLADE_HOOKUP_OBJECT (vote_id_mp, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (vote_id_mp, identifiant_vote, "identifiant_vote");
  GLADE_HOOKUP_OBJECT (vote_id_mp, mot_passecond, "mot_passecond");
  GLADE_HOOKUP_OBJECT (vote_id_mp, label7, "label7");
  GLADE_HOOKUP_OBJECT (vote_id_mp, label6, "label6");
  GLADE_HOOKUP_OBJECT (vote_id_mp, Bouton_vote, "Bouton_vote");
  GLADE_HOOKUP_OBJECT_NO_REF (vote_id_mp, tooltips, "tooltips");

  return vote_id_mp;
}

